# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-11 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appschools', '0003_auto_20180311_2209'),
        ('appprofiles', '0010_auto_20180317_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('description', models.TextField()),
                ('semester', models.IntegerField(null=True)),
                ('is_final', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appschools.SchoolClass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appprofiles.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='grades',
            name='school_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appschoolsubjects.SchoolSubject'),
        ),
        migrations.AddField(
            model_name='grades',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appprofiles.Profile'),
        ),
    ]
