# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-12 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appschoolsubjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsubject',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appschools.SchoolClass'),
        ),
    ]
