# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appschoolsubjects', '0002_auto_20180412_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
