# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appschoolsubjects', '0003_auto_20180512_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='schoolsubject',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
