# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-11 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appschools', '0002_schoolclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appschools.School'),
        ),
    ]
