# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-24 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appschools', '0003_auto_20180311_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
