# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appschools', '0006_school_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='county',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='class_direction',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='class_number',
            field=models.CharField(max_length=5),
        ),
    ]
