# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 20:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appschools', '0007_auto_20180603_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='first_shift_begin',
            field=models.TimeField(default=datetime.time(7, 30)),
        ),
        migrations.AddField(
            model_name='school',
            name='second_shift_begin',
            field=models.TimeField(default=datetime.time(13, 30)),
        ),
    ]
