# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appschoolscheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolscheduler',
            old_name='razred',
            new_name='school_class',
        ),
    ]
