# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appschoolscheduler', '0002_auto_20180723_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolscheduler',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
