# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appprofiles', '0013_profile_theme'),
        ('appschoolscheduler', '0003_schoolscheduler_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolscheduler',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appprofiles.Profile'),
        ),
    ]
