# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 22:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appprofiles', '0013_profile_theme'),
        ('appschoolscheduler', '0004_schoolscheduler_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.TextField(null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('scheduled_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appschoolscheduler.SchoolScheduler')),
            ],
        ),
        migrations.CreateModel(
            name='PresencOfStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('justified', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('scheduled_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appschoolscheduler.SchoolScheduler')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appprofiles.Profile')),
            ],
        ),
    ]
