# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appschoolscheduler', '0005_lessonplan_presencofstudent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PresencOfStudent',
            new_name='PresenceOfStudent',
        ),
    ]
