# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-06 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appprofiles', '0002_auto_20180305_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.ForeignKey(blank=True, default=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='appschools.School'),
        ),
    ]
