# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-07 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appschools', '0002_schoolclass'),
        ('appprofiles', '0004_auto_20180306_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appschools.SchoolClass'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appschools.School'),
        ),
    ]
