# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-11 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprofiles', '0005_auto_20180307_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='unkown.jpg', upload_to=''),
        ),
    ]
