# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-17 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprofiles', '0006_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='unkown.jpg', upload_to='media/'),
        ),
    ]
