# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-17 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprofiles', '0007_auto_20180317_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='unknown.png', upload_to='media/'),
        ),
    ]
