# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-17 22:02
from __future__ import unicode_literals

import appprofiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprofiles', '0009_auto_20180317_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_images/unknown.png', upload_to=appprofiles.models.user_directory_path),
        ),
    ]
