# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-24 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appprofiles', '0010_auto_20180317_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_key', models.CharField(max_length=20)),
                ('activated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appprofiles.Profile')),
            ],
        ),
    ]
