# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprofiles', '0012_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(default='dark', max_length=30),
        ),
    ]
