# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-10 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessages',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
