# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-10 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmessages', '0002_auto_20180410_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessages',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
